import { Suggestion, DashboardStats } from './types';

export const mockSuggestions: Suggestion[] = [
  {
    id: '1',
    title: 'Digitalisierung der Antragsbearbeitung',
    problemDescription: 'Aktuell werden viele Anträge noch papierbasiert bearbeitet, was zu langen Bearbeitungszeiten und hohem Papierverbrauch führt.',
    solutionDescription: 'Einführung eines digitalen Antragssystems mit automatischer Weiterleitung und elektronischer Unterschrift.',
    expectedBenefit: 'Reduzierung der Bearbeitungszeit um 60%, Einsparung von ca. 10.000 Blatt Papier pro Jahr.',
    category: 'Prozesse / Verwaltung',
    scope: 'kammer',
    estimatedSavings: '15.000 € pro Jahr',
    feasibility: 'Hoch – vergleichbare Systeme existieren bereits bei anderen Kammern.',
    teamMembers: [
      { id: '1', name: 'Maria Schmidt', email: 'maria.schmidt@hwk-berlin.de' },
      { id: '2', name: 'Thomas Müller', email: 'thomas.mueller@hwk-berlin.de' },
    ],
    attachments: [],
    status: 'umgesetzt',
    premiumClass: 3,
    premiumChoice: 'geld',
    juryComment: 'Exzellenter Vorschlag mit hohem Einsparpotenzial. Wird sofort umgesetzt.',
    submittedBy: 'Maria Schmidt',
    submittedAt: '2025-01-15',
    updatedAt: '2025-03-01',
  },
  {
    id: '2',
    title: 'Ergonomische Arbeitsplatzgestaltung',
    problemDescription: 'Viele Mitarbeitende klagen über Rückenschmerzen aufgrund nicht ergonomischer Bürostühle und Tische.',
    solutionDescription: 'Schrittweise Anschaffung höhenverstellbarer Schreibtische und ergonomischer Bürostühle für alle Arbeitsplätze.',
    expectedBenefit: 'Reduzierung von Krankheitstagen, höhere Mitarbeiterzufriedenheit.',
    category: 'Arbeitsbedingungen',
    scope: 'kammer',
    feasibility: 'Mittel – Budgetplanung über 2 Jahre notwendig.',
    teamMembers: [],
    attachments: [],
    status: 'angenommen',
    premiumClass: 3,
    juryComment: 'Wichtiger Vorschlag für die Gesundheit der Mitarbeitenden.',
    submittedBy: 'Anna Weber',
    submittedAt: '2025-02-10',
    updatedAt: '2025-02-28',
  },
  {
    id: '3',
    title: 'LED-Beleuchtung in allen Gebäuden',
    problemDescription: 'Die Beleuchtung in vielen Räumen besteht noch aus veralteten Leuchtstoffröhren mit hohem Energieverbrauch.',
    solutionDescription: 'Umrüstung aller Räume auf LED-Beleuchtung mit Bewegungsmeldern.',
    expectedBenefit: 'Energieeinsparung von ca. 40%, weniger Wartungsaufwand.',
    category: 'Umwelt / Nachhaltigkeit',
    scope: 'kammer',
    estimatedSavings: '8.000 € pro Jahr',
    feasibility: 'Hoch – schnelle Umsetzung möglich.',
    teamMembers: [],
    attachments: [],
    status: 'in_pruefung',
    submittedBy: 'Peter Klein',
    submittedAt: '2025-03-01',
    updatedAt: '2025-03-05',
  },
  {
    id: '4',
    title: 'Interne Wissensdatenbank',
    problemDescription: 'Wissen geht verloren, wenn Mitarbeitende die Abteilung wechseln oder in Rente gehen.',
    solutionDescription: 'Aufbau einer internen Wiki-Plattform für Prozessdokumentation und FAQ.',
    expectedBenefit: 'Schnellere Einarbeitung neuer Mitarbeitender, weniger Wissenverlust.',
    category: 'Personal / Organisation',
    scope: 'kammer',
    feasibility: 'Mittel – erfordert initiale Dokumentationsarbeit.',
    teamMembers: [
      { id: '3', name: 'Lisa Braun', email: 'lisa.braun@hwk-berlin.de' },
    ],
    attachments: [],
    status: 'eingereicht',
    submittedBy: 'Jan Hoffmann',
    submittedAt: '2025-03-07',
    updatedAt: '2025-03-07',
  },
  {
    id: '5',
    title: 'Optimierung der Telefonanlage',
    problemDescription: 'Häufige Beschwerden über schlechte Erreichbarkeit und veraltete Telefonanlage.',
    solutionDescription: 'Migration auf VoIP-System mit automatischer Anrufweiterleitung und Warteschleifenmanagement.',
    expectedBenefit: 'Bessere Erreichbarkeit, moderne Funktionen wie Videokonferenzen.',
    category: 'Dienstleistungsqualität',
    scope: 'kammer',
    estimatedSavings: '5.000 € pro Jahr',
    feasibility: 'Hoch',
    teamMembers: [],
    attachments: [],
    status: 'abgelehnt',
    juryComment: 'Die Migration ist bereits im IT-Jahresplan vorgesehen und fällt damit in den regulären Aufgabenbereich.',
    submittedBy: 'Sabine Richter',
    submittedAt: '2025-01-20',
    updatedAt: '2025-02-15',
  },
];

export const mockStats: DashboardStats = {
  totalSubmitted: 42,
  inReview: 8,
  implemented: 12,
  savedResources: '48.500 €',
};
